//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStockContext : DbContext
    {
        public dbStockContext()
            : base("name=dbStockContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<CommandeClient> CommandeClients { get; set; }
        public virtual DbSet<Entree> Entrees { get; set; }
        public virtual DbSet<EtatStock> EtatStocks { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<Fournisseur> Fournisseurs { get; set; }
        public virtual DbSet<Ligne_Entree> Ligne_Entree { get; set; }
        public virtual DbSet<Ligne_Facture> Ligne_Facture { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<Sortie> Sorties { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
