//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entree()
        {
            this.EtatStocks = new HashSet<EtatStock>();
        }
    
        public int code_Entree { get; set; }
        public int code_Produit { get; set; }
        public int code_Stock { get; set; }
        public int code_Fournisseur { get; set; }
        public string nom_Entree { get; set; }
        public int qte_Entree { get; set; }
        public int total { get; set; }
    
        public virtual EtatStock EtatStock { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Produit Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtatStock> EtatStocks { get; set; }
    }
}
