//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtatStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EtatStock()
        {
            this.Entrees = new HashSet<Entree>();
        }
    
        public int code_Stock { get; set; }
        public int code_Entree { get; set; }
        public int code_Sortie { get; set; }
        public int code_Produit { get; set; }
        public int qteEnStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entree> Entrees { get; set; }
        public virtual Entree Entree { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Sortie Sortie { get; set; }
    }
}
