//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_Facture
    {
        public long code_Facture { get; set; }
        public int code_Produit { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual Facture Facture { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
