//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sortie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sortie()
        {
            this.EtatStocks = new HashSet<EtatStock>();
            this.Produits = new HashSet<Produit>();
        }
    
        public int code_Sortie { get; set; }
        public int code_Client { get; set; }
        public int code_Produit { get; set; }
        public string date_Commande { get; set; }
        public int total_HT { get; set; }
        public double TVA { get; set; }
        public int total_TTC { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtatStock> EtatStocks { get; set; }
        public virtual Produit Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit> Produits { get; set; }
    }
}
