//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int code_Utilisateur { get; set; }
        public string prenom_Utilisateur { get; set; }
        public string nom_Utilisateur { get; set; }
        public string dateNaissance_Utilisateur { get; set; }
        public string lieuNaissance_Utilisateur { get; set; }
        public string nationalite_Utilisateur { get; set; }
        public string numero_CNI { get; set; }
        public string pays_Utilisateur { get; set; }
        public string quartier_Utilisateur { get; set; }
        public string telephone_Utilisateur { get; set; }
        public string username_Utilisateur { get; set; }
        public string password_Utilisateur { get; set; }
    }
}
